name: "Update Docker Image"

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io/tomadamatkinson-actions/github-docker-repository
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Checkout Repository
        uses: actions/checkout@v2

      - run: ls

      - name: Build Image
        run: docker build -t ${{ github.repository }}:latest Dockerfile

      - name: Images
        run: docker images
